#export http_proxy=socks5://127.0.0.1:9050  # Tor
#export http_proxy=socks5://127.0.0.1:8118  # Privoxy
export http_proxy=socks5://127.0.0.1:3128  # Squid
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
export FTP_PROXY=$http_proxy
export RSYNC_PROXY=$http_proxy
